"""Add content_vector to posts

Revision ID: 303db20f35e4
Revises: 84ce14748530
Create Date: 2025-10-04 13:34:39.126569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303db20f35e4'
down_revision: Union[str, Sequence[str], None] = '84ce14748530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_vector', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content_vector')
    # ### end Alembic commands ###
