"""Add thumbnail_url to posts table

Revision ID: 3b0a6398e7bd
Revises: 303db20f35e4
Create Date: 2025-10-04 14:36:30.341562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0a6398e7bd'
down_revision: Union[str, Sequence[str], None] = '303db20f35e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.drop_column('posts', 'content_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_vector', sa.BLOB(), nullable=True))
    op.drop_column('posts', 'thumbnail_url')
    # ### end Alembic commands ###
