"""Add video_link to posts table

Revision ID: ade540faac2b
Revises: 3b0a6398e7bd
Create Date: 2025-10-04 15:22:55.297850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade540faac2b'
down_revision: Union[str, Sequence[str], None] = '3b0a6398e7bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('video_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'video_link')
    # ### end Alembic commands ###
